server:
  port: ${PORT:8761}

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:dwi-eureka.railway.internal}
  server:
    renewal-percent-threshold: 0.90